# This FUNDING.yml shows the community how to support this project. Please see our repository funding links documentation for more information on formatting and what is and isn't allowed in this file.

# PAYTM on <+91 7977486513>

custom: ['www.paypal.com/donate/projects/getAir2U.html']
